{
 "title": "ipv4 vs ipv6",
 "time": { "from": "2025-11-20T06:00:00.000Z", "to": "2025-11-21T05:59:59.000Z" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n<h1>How much of the traffic is IPv4 vs IPv6?</h1>\n</center>\n\n<style>\n  @import url('https://fonts.googleapis.com/css2?family=Stack+Sans+Text:wght@200..700&display=swap');\n  h1 {\n    font-family: \"Stack Sans Text\", sans-serif;\n    font-size: 32pt;\n    font-weight: 500;\n    color: #c2b8fd;\n  }\n</style>"
   }
  },
  {
   "title": "ipv4 vs ipv6 (% breakdown)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(start_time) AS time,\n  -- ip_version,\n  SUM(bit_count)/8 AS Volume\nFROM\n  metranova.data_flow\nWHERE\n  $__timeFilter(time)\n  AND ip_version = 6\nGROUP BY\n  time\nORDER BY\n  time ASC\n"
    },
    {
     "rawSql": "SELECT\n  $__timeInterval(start_time) AS time,\n  -- ip_version,\n  SUM(bit_count)/8 AS Volume\nFROM\n  metranova.data_flow\nWHERE\n  $__timeFilter(time)\n  AND ip_version = 4\nGROUP BY\n  time\nORDER BY\n  time ASC\n"
    }
   ]
  },
  {
   "title": "Booths with the most ipv6 Traffic",
   "type": "table",
   "gridPos": { "h": 25, "w": 9, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "rawSql": "  SELECT Booth, Organization, sum(Volume)\n  FROM (\n  SELECT \n  dictGet('meta_ip_scinet_dict', 'id', ext.dst_ip_scinet_ref) AS Booth,\n  dictGet('meta_ip_scinet_dict', 'organization_name', ext.dst_ip_scinet_ref) AS Organization,\n  sum(bit_count)/8 AS Volume\n  FROM \"metranova\".\"data_flow\" \n  WHERE Booth IS NOT NULL\n    AND ip_version = 6\n  GROUP BY Booth, Organization\n  ORDER BY Volume DESC\n  LIMIT 100\n\n  UNION ALL\n\n  SELECT \n  dictGet('meta_ip_scinet_dict', 'id', ext.src_ip_scinet_ref) AS Booth,\n  dictGet('meta_ip_scinet_dict', 'organization_name', ext.src_ip_scinet_ref) AS Organization,\n  sum(bit_count)/8 AS Volume\n  FROM \"metranova\".\"data_flow\" \n  WHERE Booth IS NOT NULL\n    AND ip_version = 6\n  GROUP BY Booth, Organization\n  ORDER BY Volume DESC\n  LIMIT 100\n  )\n  GROUP BY Booth, Organization\n  ORDER BY sum(Volume) DESC\n  LIMIT 20"
    }
   ]
  },
  {
   "title": "ipv4 vs ipv6",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(start_time) AS time,\n  -- ip_version,\n  SUM(bit_count)/$__interval_s AS Rate\nFROM\n  metranova.data_flow\nWHERE\n  $__timeFilter(time)\n  AND ip_version = 6\nGROUP BY\n  time\nORDER BY\n  time ASC\n"
    },
    {
     "rawSql": "SELECT\n  $__timeInterval(start_time) AS time,\n  -- ip_version,\n  SUM(bit_count)/$__interval_s AS Rate\nFROM\n  metranova.data_flow\nWHERE\n  $__timeFilter(time)\n  AND ip_version = 4\nGROUP BY\n  time\nORDER BY\n  time ASC\n"
    }
   ]
  }
 ]
}