{
 "title": "Traffic Overview (volume)",
 "time": { "from": "2025-11-20T06:00:00.000Z", "to": "2025-11-21T05:59:59.000Z" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n<h1>How MUCH data is moving over SCinet?</h1>\n</center>\n\n<style>\n  @import url('https://fonts.googleapis.com/css2?family=Stack+Sans+Text:wght@200..700&display=swap');\n  h1 {\n    font-family: \"Stack Sans Text\", sans-serif;\n    font-size: 32pt;\n    font-weight: 500;\n    color: #c2b8fd;\n  }\n</style>"
   }
  },
  {
   "title": "Traffic Volume",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 22, "x": 1, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(start_time) AS time,\nSUM(bit_count)/8 AS Volume\nFROM\n  metranova.data_flow\nWHERE\n  $__timeFilter(time) AND device_id != '140.221.135.2'\nGROUP BY\n  time\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Booths with the most Incoming Traffic (vol)",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 1, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT \n  dictGet('meta_ip_scinet_dict', 'id', ext.dst_ip_scinet_ref) AS Booth,\n  dictGet('meta_ip_scinet_dict', 'organization_name', ext.dst_ip_scinet_ref) AS Organization,\n  sum(bit_count)/8 AS Volume\n  FROM \"metranova\".\"data_flow\" \n  WHERE Booth IS NOT NULL\n  GROUP BY Booth, Organization\n  ORDER BY Volume DESC"
    }
   ]
  },
  {
   "title": "Booths with the most Outgoing Traffic (vol)",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT \n    dictGet('meta_ip_scinet_dict', 'id', ext.src_ip_scinet_ref) AS Booth,\n  dictGet('meta_ip_scinet_dict', 'organization_name', ext.src_ip_scinet_ref) AS Organization,\n  sum(bit_count)/8 AS Volume\n  FROM \"metranova\".\"data_flow\" \n  WHERE Booth IS NOT NULL\n  GROUP BY Booth, Organization\n  ORDER BY Volume DESC"
    }
   ]
  }
 ]
}